/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "surface-dim": "#d3daef",
        "on-secondary-fixed-variant": "#005049",
        "tertiary-fixed-dim": "#ffb77d",
        "inverse-surface": "#293040",
        "on-primary": "#ffffff",
        "on-error-container": "#93000a",
        "on-tertiary-container": "#fc922b",
        "error": "#ba1a1a",
        "tertiary": "#442100",
        "on-surface": "#141b2b",
        "surface-container-highest": "#dce2f7",
        "primary": "#00236f",
        "background": "#f9f9ff",
        "on-primary-fixed-variant": "#264191",
        "on-primary-fixed": "#00164e",
        "primary-fixed": "#dce1ff",
        "surface-container-lowest": "#ffffff",
        "on-primary-container": "#90a8ff",
        "error-container": "#ffdad6",
        "on-secondary-fixed": "#00201d",
        "secondary": "#006a61",
        "tertiary-container": "#653400",
        "surface-container": "#e9edff",
        "on-tertiary": "#ffffff",
        "secondary-fixed": "#89f5e7",
        "on-surface-variant": "#444651",
        "primary-fixed-dim": "#b6c4ff",
        "tertiary-fixed": "#ffdcc3",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed": "#2f1500",
        "inverse-primary": "#b6c4ff",
        "surface-tint": "#4059aa",
        "secondary-container": "#86f2e4",
        "outline": "#757682",
        "inverse-on-surface": "#edf0ff",
        "surface": "#f9f9ff",
        "surface-bright": "#f9f9ff",
        "surface-container-low": "#f1f3ff",
        "on-secondary-container": "#006f66",
        "surface-container-high": "#e1e8fd",
        "on-background": "#141b2b",
        "outline-variant": "#c5c5d3",
        "on-tertiary-fixed-variant": "#6e3900",
        "on-error": "#ffffff",
        "secondary-fixed-dim": "#6bd8cb",
        "primary-container": "#1e3a8a",
        "surface-variant": "#dce2f7"
      },
      "borderRadius": {
        "DEFAULT": "0.5rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "fontFamily": {
        "headline": ["Inter"],
        "body": ["Inter"],
        "label": ["Inter"]
      }
    },
  },
  plugins: [],
}
